name: 'elasticity_project'
version: '1.0.0'
config-version: 2

profile: 'elasticity_project'

model-paths: ["models"]
seed-paths: ['data']

models:
  elasticity_project:
    models:
      materialized: ephemeral